import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ListProvider } from "@/redux/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${inter.className} bg-[#003C43]`}>
        <ListProvider>{children}</ListProvider>
      </body>
    </html>
  );
}
